# File used for local development DB startup
version: '2.0'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: adventure-crm
      MYSQL_ROOT_PASSWORD: letmein
